onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /ControllerTop/clk
add wave -noupdate /ControllerTop/cntrIntf/clk
add wave -noupdate /ControllerTop/cntrIntf/DIO
add wave -noupdate /ControllerTop/cntrIntf/cntrl_in
add wave -noupdate /ControllerTop/cntrIntf/cntrl_sel
add wave -noupdate /ControllerTop/cntrIntf/cntrl_we
add wave -noupdate /ControllerTop/cntrIntf/cntrl_re
add wave -noupdate /ControllerTop/cntrIntf/nfc_done
add wave -noupdate /ControllerTop/cntrIntf/ALE
add wave -noupdate /ControllerTop/cntrIntf/CLE
add wave -noupdate /ControllerTop/cntrIntf/wEn
add wave -noupdate /ControllerTop/cntrIntf/rEn
add wave -noupdate /ControllerTop/cntrIntf/command_error
add wave -noupdate /ControllerTop/cntrIntf/cEn
add wave -noupdate /ControllerTop/cntrIntf/nfc_cmd
add wave -noupdate /ControllerTop/cntrIntf/RWA
add wave -noupdate /ControllerTop/cntrIntf/Reset
add wave -noupdate /ControllerTop/cntrIntf/nfc_start
add wave -noupdate /ControllerTop/cntrIntf/status
add wave -noupdate /ControllerTop/cntrIntf/cntrl_out
add wave -noupdate /ControllerTop/cntrIntf/buf_cntrl_status
add wave -noupdate /ControllerTop/cntrIntf/host_buf_status
add wave -noupdate /ControllerTop/cntr/cntrBus/clk
add wave -noupdate /ControllerTop/cntr/cntrBus/DIO
add wave -noupdate /ControllerTop/cntr/cntrBus/cntrl_in
add wave -noupdate /ControllerTop/cntr/cntrBus/cntrl_sel
add wave -noupdate /ControllerTop/cntr/cntrBus/cntrl_we
add wave -noupdate /ControllerTop/cntr/cntrBus/cntrl_re
add wave -noupdate /ControllerTop/cntr/cntrBus/nfc_done
add wave -noupdate /ControllerTop/cntr/cntrBus/ALE
add wave -noupdate /ControllerTop/cntr/cntrBus/CLE
add wave -noupdate /ControllerTop/cntr/cntrBus/wEn
add wave -noupdate /ControllerTop/cntr/cntrBus/rEn
add wave -noupdate /ControllerTop/cntr/cntrBus/command_error
add wave -noupdate /ControllerTop/cntr/cntrBus/cEn
add wave -noupdate /ControllerTop/cntr/cntrBus/nfc_cmd
add wave -noupdate /ControllerTop/cntr/cntrBus/RWA
add wave -noupdate /ControllerTop/cntr/cntrBus/Reset
add wave -noupdate /ControllerTop/cntr/cntrBus/nfc_start
add wave -noupdate /ControllerTop/cntr/cntrBus/status
add wave -noupdate /ControllerTop/cntr/cntrBus/cntrl_out
add wave -noupdate /ControllerTop/cntr/cntrBus/buf_cntrl_status
add wave -noupdate /ControllerTop/cntr/cntrBus/host_buf_status
add wave -noupdate /ControllerTop/cntr_tb/DIO_out
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/clk
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/DIO
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/cntrl_in
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/cntrl_sel
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/cntrl_we
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/cntrl_re
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/nfc_done
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/ALE
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/CLE
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/wEn
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/rEn
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/command_error
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/cEn
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/nfc_cmd
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/RWA
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/Reset
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/nfc_start
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/status
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/cntrl_out
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/buf_cntrl_status
add wave -noupdate /ControllerTop/cntr_tb/cntrBus_tb/host_buf_status
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {35735 ns} {41788 ns}
