onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /MemoryControllerTop/clk
add wave -noupdate /MemoryControllerTop/mcIntf/clk
add wave -noupdate /MemoryControllerTop/mcIntf/DIO_memCntrl
add wave -noupdate /MemoryControllerTop/mcIntf/buf_out
add wave -noupdate /MemoryControllerTop/mcIntf/nfc_done
add wave -noupdate /MemoryControllerTop/mcIntf/command_error
add wave -noupdate /MemoryControllerTop/mcIntf/ALE
add wave -noupdate /MemoryControllerTop/mcIntf/CLE
add wave -noupdate /MemoryControllerTop/mcIntf/wEn
add wave -noupdate /MemoryControllerTop/mcIntf/rEn
add wave -noupdate /MemoryControllerTop/mcIntf/cEn
add wave -noupdate /MemoryControllerTop/mcIntf/buf_in
add wave -noupdate /MemoryControllerTop/mcIntf/buf_sel
add wave -noupdate /MemoryControllerTop/mcIntf/buf_we
add wave -noupdate /MemoryControllerTop/mcIntf/buf_re
add wave -noupdate /MemoryControllerTop/mcIntf/nfc_cmd
add wave -noupdate /MemoryControllerTop/mcIntf/RWA
add wave -noupdate /MemoryControllerTop/mcIntf/Reset
add wave -noupdate /MemoryControllerTop/mcIntf/nfc_start
add wave -noupdate /MemoryControllerTop/mcIntf/status
add wave -noupdate /MemoryControllerTop/mc/cntrl_sel
add wave -noupdate /MemoryControllerTop/mc/cntrl_we
add wave -noupdate /MemoryControllerTop/mc/cntrl_re
add wave -noupdate /MemoryControllerTop/mc/cntrl_in
add wave -noupdate /MemoryControllerTop/mc/cntrl_out
add wave -noupdate /MemoryControllerTop/mc/buf_cntrl_status
add wave -noupdate /MemoryControllerTop/mc/host_buf_status
add wave -noupdate /MemoryControllerTop/mc/DIO
add wave -noupdate /MemoryControllerTop/mc/mcBus/clk
add wave -noupdate /MemoryControllerTop/mc/mcBus/DIO_memCntrl
add wave -noupdate /MemoryControllerTop/mc/mcBus/buf_out
add wave -noupdate /MemoryControllerTop/mc/mcBus/nfc_done
add wave -noupdate /MemoryControllerTop/mc/mcBus/command_error
add wave -noupdate /MemoryControllerTop/mc/mcBus/ALE
add wave -noupdate /MemoryControllerTop/mc/mcBus/CLE
add wave -noupdate /MemoryControllerTop/mc/mcBus/wEn
add wave -noupdate /MemoryControllerTop/mc/mcBus/rEn
add wave -noupdate /MemoryControllerTop/mc/mcBus/cEn
add wave -noupdate /MemoryControllerTop/mc/mcBus/buf_in
add wave -noupdate /MemoryControllerTop/mc/mcBus/buf_sel
add wave -noupdate /MemoryControllerTop/mc/mcBus/buf_we
add wave -noupdate /MemoryControllerTop/mc/mcBus/buf_re
add wave -noupdate /MemoryControllerTop/mc/mcBus/nfc_cmd
add wave -noupdate /MemoryControllerTop/mc/mcBus/RWA
add wave -noupdate /MemoryControllerTop/mc/mcBus/Reset
add wave -noupdate /MemoryControllerTop/mc/mcBus/nfc_start
add wave -noupdate /MemoryControllerTop/mc/mcBus/status
add wave -noupdate /MemoryControllerTop/mc/cntrl/clk
add wave -noupdate /MemoryControllerTop/mc/cntrl/DIO
add wave -noupdate /MemoryControllerTop/mc/cntrl/cntrl_in
add wave -noupdate /MemoryControllerTop/mc/cntrl/cntrl_sel
add wave -noupdate /MemoryControllerTop/mc/cntrl/cntrl_we
add wave -noupdate /MemoryControllerTop/mc/cntrl/cntrl_re
add wave -noupdate /MemoryControllerTop/mc/cntrl/nfc_done
add wave -noupdate /MemoryControllerTop/mc/cntrl/ALE
add wave -noupdate /MemoryControllerTop/mc/cntrl/CLE
add wave -noupdate /MemoryControllerTop/mc/cntrl/wEn
add wave -noupdate /MemoryControllerTop/mc/cntrl/rEn
add wave -noupdate /MemoryControllerTop/mc/cntrl/command_error
add wave -noupdate /MemoryControllerTop/mc/cntrl/cEn
add wave -noupdate /MemoryControllerTop/mc/cntrl/nfc_cmd
add wave -noupdate /MemoryControllerTop/mc/cntrl/RWA
add wave -noupdate /MemoryControllerTop/mc/cntrl/Reset
add wave -noupdate /MemoryControllerTop/mc/cntrl/nfc_start
add wave -noupdate /MemoryControllerTop/mc/cntrl/status
add wave -noupdate /MemoryControllerTop/mc/cntrl/cntrl_out
add wave -noupdate /MemoryControllerTop/mc/cntrl/buf_cntrl_status
add wave -noupdate /MemoryControllerTop/mc/cntrl/host_buf_status
add wave -noupdate /MemoryControllerTop/mc/cntrl/DIO_out
add wave -noupdate /MemoryControllerTop/mc/cntrl/command
add wave -noupdate /MemoryControllerTop/mc/cntrl/cur_state
add wave -noupdate /MemoryControllerTop/mc/cntrl/next_state
add wave -noupdate /MemoryControllerTop/mc/bufm/clk
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_sel
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_we
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_re
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_sel
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_we
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_re
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_in
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_in
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_out
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_out
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_cntrl_status
add wave -noupdate /MemoryControllerTop/mc/bufm/host_buf_status
add wave -noupdate /MemoryControllerTop/mc/bufm/host_addr
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_addr
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_read_flag
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_read_flag
add wave -noupdate /MemoryControllerTop/mc/bufm/buf_write_flag
add wave -noupdate /MemoryControllerTop/mc/bufm/cntrl_write_flag
add wave -noupdate /MemoryControllerTop/mc_tb/DIO_out
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/clk
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/DIO_memCntrl
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/buf_out
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/nfc_done
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/command_error
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/ALE
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/CLE
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/wEn
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/rEn
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/cEn
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/buf_in
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/buf_sel
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/buf_we
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/buf_re
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/nfc_cmd
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/RWA
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/Reset
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/nfc_start
add wave -noupdate /MemoryControllerTop/mc_tb/mcBus_tb/status
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {39485 ns} {41485 ns}
