onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Top/clk
add wave -noupdate /Top/reset
add wave -noupdate /Top/ncIntf/clk
add wave -noupdate /Top/ncIntf/reset
add wave -noupdate /Top/ncIntf/buf_out
add wave -noupdate /Top/ncIntf/nfc_done
add wave -noupdate /Top/ncIntf/command_error
add wave -noupdate /Top/ncIntf/buf_in
add wave -noupdate /Top/ncIntf/buf_sel
add wave -noupdate /Top/ncIntf/buf_we
add wave -noupdate /Top/ncIntf/buf_re
add wave -noupdate /Top/ncIntf/nfc_cmd
add wave -noupdate /Top/ncIntf/RWA
add wave -noupdate /Top/ncIntf/nfc_start
add wave -noupdate /Top/ncIntf/NC_driver_cb/nfc_start
add wave -noupdate /Top/ncIntf/NC_driver_cb/RWA
add wave -noupdate /Top/ncIntf/NC_driver_cb/nfc_cmd
add wave -noupdate /Top/ncIntf/NC_driver_cb/buf_re
add wave -noupdate /Top/ncIntf/NC_driver_cb/buf_we
add wave -noupdate /Top/ncIntf/NC_driver_cb/buf_sel
add wave -noupdate /Top/ncIntf/NC_driver_cb/buf_in
add wave -noupdate /Top/ncIntf/NC_driver_cb/command_error
add wave -noupdate /Top/ncIntf/NC_driver_cb/nfc_done
add wave -noupdate /Top/ncIntf/NC_driver_cb/buf_out
add wave -noupdate /Top/ncIntf/NC_driver_cb/NC_driver_cb_event
add wave -noupdate /Top/ncIntf/NC_monitor_cb/nfc_start
add wave -noupdate /Top/ncIntf/NC_monitor_cb/RWA
add wave -noupdate /Top/ncIntf/NC_monitor_cb/nfc_cmd
add wave -noupdate /Top/ncIntf/NC_monitor_cb/buf_re
add wave -noupdate /Top/ncIntf/NC_monitor_cb/buf_we
add wave -noupdate /Top/ncIntf/NC_monitor_cb/buf_sel
add wave -noupdate /Top/ncIntf/NC_monitor_cb/buf_in
add wave -noupdate /Top/ncIntf/NC_monitor_cb/command_error
add wave -noupdate /Top/ncIntf/NC_monitor_cb/nfc_done
add wave -noupdate /Top/ncIntf/NC_monitor_cb/buf_out
add wave -noupdate /Top/ncIntf/NC_monitor_cb/NC_monitor_cb_event
add wave -noupdate /Top/test/ncIntf/clk
add wave -noupdate /Top/test/ncIntf/reset
add wave -noupdate /Top/test/ncIntf/buf_out
add wave -noupdate /Top/test/ncIntf/nfc_done
add wave -noupdate /Top/test/ncIntf/command_error
add wave -noupdate /Top/test/ncIntf/buf_in
add wave -noupdate /Top/test/ncIntf/buf_sel
add wave -noupdate /Top/test/ncIntf/buf_we
add wave -noupdate /Top/test/ncIntf/buf_re
add wave -noupdate /Top/test/ncIntf/nfc_cmd
add wave -noupdate /Top/test/ncIntf/RWA
add wave -noupdate /Top/test/ncIntf/nfc_start
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/nfc_start
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/RWA
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/nfc_cmd
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/buf_re
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/buf_we
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/buf_sel
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/buf_in
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/command_error
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/nfc_done
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/buf_out
add wave -noupdate /Top/test/ncIntf/NC_driver_cb/NC_driver_cb_event
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/nfc_start
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/RWA
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/nfc_cmd
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/buf_re
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/buf_we
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/buf_sel
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/buf_in
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/command_error
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/nfc_done
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/buf_out
add wave -noupdate /Top/test/ncIntf/NC_monitor_cb/NC_monitor_cb_event
add wave -noupdate /Top/dut/clk
add wave -noupdate /Top/dut/buf_out
add wave -noupdate /Top/dut/nfc_done
add wave -noupdate /Top/dut/command_error
add wave -noupdate /Top/dut/buf_in
add wave -noupdate /Top/dut/buf_sel
add wave -noupdate /Top/dut/buf_we
add wave -noupdate /Top/dut/buf_re
add wave -noupdate /Top/dut/nfc_cmd
add wave -noupdate /Top/dut/RWA
add wave -noupdate /Top/dut/Reset
add wave -noupdate /Top/dut/nfc_start
add wave -noupdate /Top/dut/DIO_memCntrl
add wave -noupdate /Top/dut/ALE
add wave -noupdate /Top/dut/CLE
add wave -noupdate /Top/dut/wEn
add wave -noupdate /Top/dut/rEn
add wave -noupdate /Top/dut/cEn
add wave -noupdate /Top/dut/status
add wave -noupdate /Top/dut/MC/DIO_memCntrl
add wave -noupdate /Top/dut/MC/buf_out
add wave -noupdate /Top/dut/MC/nfc_done
add wave -noupdate /Top/dut/MC/command_error
add wave -noupdate /Top/dut/MC/ALE
add wave -noupdate /Top/dut/MC/CLE
add wave -noupdate /Top/dut/MC/wEn
add wave -noupdate /Top/dut/MC/rEn
add wave -noupdate /Top/dut/MC/cEn
add wave -noupdate /Top/dut/MC/buf_in
add wave -noupdate /Top/dut/MC/buf_sel
add wave -noupdate /Top/dut/MC/buf_we
add wave -noupdate /Top/dut/MC/buf_re
add wave -noupdate /Top/dut/MC/nfc_cmd
add wave -noupdate /Top/dut/MC/RWA
add wave -noupdate /Top/dut/MC/Reset
add wave -noupdate /Top/dut/MC/nfc_start
add wave -noupdate /Top/dut/MC/clk
add wave -noupdate /Top/dut/MC/status
add wave -noupdate /Top/dut/MC/cntrl_sel
add wave -noupdate /Top/dut/MC/cntrl_we
add wave -noupdate /Top/dut/MC/cntrl_re
add wave -noupdate /Top/dut/MC/cntrl_in
add wave -noupdate /Top/dut/MC/cntrl_out
add wave -noupdate /Top/dut/MC/buf_cntrl_status
add wave -noupdate /Top/dut/MC/host_buf_status
add wave -noupdate /Top/dut/MC/DIO
add wave -noupdate /Top/dut/MC/cntrl/clk
add wave -noupdate /Top/dut/MC/cntrl/DIO
add wave -noupdate /Top/dut/MC/cntrl/cntrl_in
add wave -noupdate /Top/dut/MC/cntrl/cntrl_sel
add wave -noupdate /Top/dut/MC/cntrl/cntrl_we
add wave -noupdate /Top/dut/MC/cntrl/cntrl_re
add wave -noupdate /Top/dut/MC/cntrl/nfc_done
add wave -noupdate /Top/dut/MC/cntrl/ALE
add wave -noupdate /Top/dut/MC/cntrl/CLE
add wave -noupdate /Top/dut/MC/cntrl/wEn
add wave -noupdate /Top/dut/MC/cntrl/rEn
add wave -noupdate /Top/dut/MC/cntrl/command_error
add wave -noupdate /Top/dut/MC/cntrl/cEn
add wave -noupdate /Top/dut/MC/cntrl/nfc_cmd
add wave -noupdate /Top/dut/MC/cntrl/RWA
add wave -noupdate /Top/dut/MC/cntrl/Reset
add wave -noupdate /Top/dut/MC/cntrl/nfc_start
add wave -noupdate /Top/dut/MC/cntrl/status
add wave -noupdate /Top/dut/MC/cntrl/cntrl_out
add wave -noupdate /Top/dut/MC/cntrl/buf_cntrl_status
add wave -noupdate /Top/dut/MC/cntrl/host_buf_status
add wave -noupdate /Top/dut/MC/cntrl/DIO_out
add wave -noupdate /Top/dut/MC/cntrl/command
add wave -noupdate /Top/dut/MC/cntrl/cur_state
add wave -noupdate /Top/dut/MC/cntrl/next_state
add wave -noupdate /Top/dut/MC/bufm/clk
add wave -noupdate /Top/dut/MC/bufm/buf_sel
add wave -noupdate /Top/dut/MC/bufm/buf_we
add wave -noupdate /Top/dut/MC/bufm/buf_re
add wave -noupdate /Top/dut/MC/bufm/cntrl_sel
add wave -noupdate /Top/dut/MC/bufm/cntrl_we
add wave -noupdate /Top/dut/MC/bufm/cntrl_re
add wave -noupdate /Top/dut/MC/bufm/buf_in
add wave -noupdate /Top/dut/MC/bufm/cntrl_in
add wave -noupdate /Top/dut/MC/bufm/cntrl_out
add wave -noupdate /Top/dut/MC/bufm/buf_out
add wave -noupdate /Top/dut/MC/bufm/buf_cntrl_status
add wave -noupdate /Top/dut/MC/bufm/host_buf_status
add wave -noupdate /Top/dut/MC/bufm/host_addr
add wave -noupdate /Top/dut/MC/bufm/cntrl_addr
add wave -noupdate /Top/dut/MC/bufm/buf_read_flag
add wave -noupdate /Top/dut/MC/bufm/cntrl_read_flag
add wave -noupdate /Top/dut/MC/bufm/buf_write_flag
add wave -noupdate /Top/dut/MC/bufm/cntrl_write_flag
add wave -noupdate /Top/dut/mem/clk
add wave -noupdate /Top/dut/mem/DIO_memCntrl
add wave -noupdate /Top/dut/mem/ALE
add wave -noupdate /Top/dut/mem/CLE
add wave -noupdate /Top/dut/mem/wEn
add wave -noupdate /Top/dut/mem/rEn
add wave -noupdate /Top/dut/mem/cEn
add wave -noupdate /Top/dut/mem/status
add wave -noupdate /Top/dut/mem/Address
add wave -noupdate /Top/dut/mem/BaseAddress
add wave -noupdate /Top/dut/mem/AddressCount
add wave -noupdate /Top/dut/mem/Command
add wave -noupdate /Top/dut/mem/DIO_out
add wave -noupdate /Top/dut/mem/write_flag
add wave -noupdate /Top/dut/mem/read_flag
add wave -noupdate /Top/dut/mem/state
add wave -noupdate /Top/dut/mem/next_state
add wave -noupdate /Top/dut/mem/validEnable
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {4997999 ns} {5000111 ns}
